name: dcc.main
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - dcc-validation-decorator/**

permissions:
  id-token: write
  contents: read 

jobs:
  build:
    defaults:
      run:
        working-directory: dcc-validation-decorator
    runs-on: ubuntu-20.04
    env:
      AWS_REGION: eu-central-1
      AWS_ACCOUNT_ID: 161247518108
    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: adopt
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - name: version
      run: |-
        APP_SHA=$(git rev-parse --short ${GITHUB_SHA})
        APP_LATEST_REV=$(git rev-list --tags --max-count=1)
        APP_LATEST_TAG=$(git describe --tags ${APP_LATEST_REV} 2> /dev/null || echo 0.0.0)
        echo "APP_VERSION=${APP_LATEST_TAG}-${APP_SHA}" >> ${GITHUB_ENV}
    - name: mvn
      run: |-
        mvn versions:set \
        --batch-mode \
        --file ./pom.xml \
        --settings ./settings.xml \
        --define newVersion="${APP_VERSION}"
        mvn clean verify \
        --batch-mode \
        --file ./pom.xml \
        --settings ./settings.xml \
        --define app.packages.username="${APP_PACKAGES_USERNAME}" \
        --define app.packages.password="${APP_PACKAGES_PASSWORD}"
      env:
        APP_PACKAGES_USERNAME: ${{ github.actor }}
        APP_PACKAGES_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/coviscan_ecr_pushpull
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and Push Container
      run: |-
        docker build . \
        --file ./docker/Native \
        --tag "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
        #--tag "${ECR_REGISTRY}/${ECR_REPOSITORY}:${APP_VERSION}"
        #docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:${APP_VERSION}"
        docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: dcc-validation-decorator
