name: dcc.main
on:
  push:
    branches:
    - main
    paths:
    - dcc-validation-decorator/**
    - .github/workflows/dcc.main.yml

jobs:
  build:
    defaults:
      run:
        working-directory: dcc-validation-decorator
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: adopt
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    - name: version
      run: |-
        APP_SHA=$(git rev-parse --short ${GITHUB_SHA})
        APP_LATEST_REV=$(git rev-list --tags --max-count=1)
        APP_LATEST_TAG=$(git describe --tags ${APP_LATEST_REV} 2> /dev/null || echo 0.0.0)
        echo "APP_VERSION=${APP_LATEST_TAG}-${APP_SHA}" >> ${GITHUB_ENV}
    - name: mvn
      run: |-
        mvn versions:set \
        --batch-mode \
        --file ./pom.xml \
        --settings ./settings.xml \
        --define newVersion="${APP_VERSION}"
        mvn clean verify \
        --batch-mode \
        --file ./pom.xml \
        --settings ./settings.xml \
        --define app.packages.username="${APP_PACKAGES_USERNAME}" \
        --define app.packages.password="${APP_PACKAGES_PASSWORD}"
      env:
        APP_PACKAGES_USERNAME: ${{ github.actor }}
        APP_PACKAGES_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - id: 'gcloud-auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_SVC_ACC_KEY_ART_REGISTRY }}
    - name: docker
      run: |-
        gcloud auth configure-docker -q

        docker build . \
        --file ./docker/Native \
        --tag "${APP_PACKAGES_URL}:${APP_VERSION}"
        docker push "${APP_PACKAGES_URL}:${APP_VERSION}"
      env:
        APP_PACKAGES_URL: us-central1-docker.pkg.dev/${{ github.repository }}/dcc-validation-decorator/dcc-validation-decorator
