name: 'lambda.authorizer.build'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read 

jobs:
  deploy_source:
    name: build and deploy lambda authorizer
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      AWS_ACCOUNT_ID: 161247518108

    defaults:
      run:
        working-directory: lambda/x509_authorizer

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install --production
      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/coviscan_iam_main
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push Lambda Authorizer Container
        run: |-
          docker build . \
          --tag "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: x509-authorizer